name: hawkeye_patro
description: "A Nepali calendar application with various features."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  lottie: ^2.7.0
  nepali_utils: ^3.0.4
  intl: ^0.18.1
  url_launcher: ^6.2.2
  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.3.10
  just_audio: ^0.9.36
  flutter_svg: ^2.0.7
  connectivity_plus: ^5.0.2
  flutter_cache_manager: ^3.3.1
  package_info_plus: ^5.0.1
  in_app_review: ^2.0.8
  share_plus: ^7.2.1
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.1.0
  flutter_dotenv: ^5.1.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  jwt_decoder: ^2.0.1
  local_auth: ^2.1.8
  uuid: ^4.0.0
  device_info_plus: ^9.1.1

  # ✅ Offline Local Data and Intelligence
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # ✅ Optional ML and location features (if needed offline as well)
  ml_algo: ^16.17.7
  weather: ^3.1.1
  geolocator: ^10.1.0

  # ✅ Optional UI Features
  flutter_html: ^3.0.0-beta.2
  fl_chart: ^0.65.0
  sensors_plus: ^4.0.2
  flutter_compass: ^0.8.0

  # ✅ Notifications
  flutter_local_notifications: ^16.3.0
  nepali_date_picker: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/news/
    - assets/images/jyotish1.png
    - assets/images/jyotish2.png
    - assets/images/jyotish3.png
    - assets/images/jyotish4.png
    - assets/animations/
    - assets/icons/

    - assets/fonts/
    - assets/data/
    - .env


flutter_native_splash:
  color: "#FF5722"
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
